[tool.poetry]
name = "kryptos-sdk"
version = "0.1.0"
description = "Tools to develop applications with Kryptos."
authors = ["Kryptos Authors <contact@whatdomain.fuckme>"]
license = "Proprietary"
packages = [{ include = "kryptos" }]

[tool.poetry.scripts]
kryptos = 'kryptos:main'

[tool.poetry.dependencies]
python = "^3.7"
docopt = "^0.6.2"
PyNaCl = "^1.4.0"
httpx = "^0.17.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
